fun main() {
    // Write some code to cause an exception
    val nums = intArrayOf(1, 2, 3)
    println(nums[5])
}
